import type { Order, Product } from "@/types";

export const products: Product[] = [
  { id:"p1", slug:"signature-berry-cake", name:"Signature Berry Cake", shortDescription:"Vanilla bean sponge, berry preserve and silk buttercream.", description:"Our celebration favourite: three layers of fragrant vanilla bean sponge, bright house-made berry preserve and light, silky buttercream. Finished by hand for an effortlessly elegant table.", category:"CUSTOM_CAKES", price:3800000, image:"/custom-cake.jpg", imagePosition:"50% 52%", badge:"Bestseller", featured:true, status:"ACTIVE", stockQuantity:8, lowStockThreshold:3, variants:[{id:"v1",name:"6 inch · serves 10",priceAdjustment:0,stockQuantity:8},{id:"v2",name:"8 inch · serves 20",priceAdjustment:1400000,stockQuantity:5},{id:"v3",name:"10 inch · serves 35",priceAdjustment:2700000,stockQuantity:3}], ingredients:"Flour, cultured butter, eggs, vanilla bean, berries, sugar, cream", allergens:["Wheat","Eggs","Dairy"], storageInstructions:"Keep chilled. Bring to room temperature 45 minutes before serving." },
  { id:"p2", slug:"classic-butter-croissant", name:"Classic Butter Croissant", shortDescription:"Crisp, honeycombed and deeply buttery.", description:"A three-day laminated croissant made with cultured butter, slow-fermented dough and plenty of patience.", category:"PASTRIES", price:450000, image:"/pastries.jpg", imagePosition:"18% 60%", badge:"Fresh today", featured:true, status:"ACTIVE", stockQuantity:24, lowStockThreshold:8, variants:[{id:"v1",name:"Single",priceAdjustment:0,stockQuantity:24},{id:"v2",name:"Box of 6",priceAdjustment:2050000,stockQuantity:4}], ingredients:"Flour, cultured butter, milk, yeast, sugar, salt", allergens:["Wheat","Dairy","Eggs"], storageInstructions:"Best enjoyed on the day of delivery." },
  { id:"p3", slug:"chocolate-croissant", name:"Dark Chocolate Croissant", shortDescription:"Laminated pastry wrapped around two dark chocolate batons.", description:"Our classic croissant dough folded around rich dark chocolate and baked until crisp and bronzed.", category:"PASTRIES", price:550000, image:"/pastries.jpg", imagePosition:"51% 40%", featured:true, status:"ACTIVE", stockQuantity:12, lowStockThreshold:5, variants:[{id:"v1",name:"Single",priceAdjustment:0,stockQuantity:12},{id:"v2",name:"Box of 6",priceAdjustment:2500000,stockQuantity:3}], ingredients:"Flour, cultured butter, dark chocolate, milk, yeast, sugar", allergens:["Wheat","Dairy","Eggs","Soy"] },
  { id:"p4", slug:"garden-berry-danish", name:"Garden Berry Danish", shortDescription:"Vanilla custard, berries and crisp laminated pastry.", description:"A crisp butter pastry with vanilla custard and a generous tumble of seasonal berries.", category:"PASTRIES", price:750000, image:"/pastries.jpg", imagePosition:"78% 70%", badge:"Seasonal", status:"ACTIVE", stockQuantity:6, lowStockThreshold:5, variants:[{id:"v1",name:"Single",priceAdjustment:0,stockQuantity:6}], ingredients:"Flour, cultured butter, vanilla, milk, eggs, seasonal berries", allergens:["Wheat","Dairy","Eggs"] },
  { id:"p5", slug:"cinnamon-knot", name:"Brown Sugar Cinnamon Knot", shortDescription:"Soft laminated layers, cinnamon and brown sugar glaze.", description:"Twisted by hand with fragrant cinnamon sugar and finished with a delicate vanilla glaze.", category:"PASTRIES", price:600000, image:"/pastries.jpg", imagePosition:"86% 32%", status:"OUT_OF_STOCK", stockQuantity:0, lowStockThreshold:4, variants:[{id:"v1",name:"Single",priceAdjustment:0,stockQuantity:0}], ingredients:"Flour, butter, cinnamon, brown sugar, vanilla", allergens:["Wheat","Dairy","Eggs"] },
  { id:"p6", slug:"bake-at-home-croissant-box", name:"Bake-at-Home Croissant Box", shortDescription:"Six proof-ready croissants for warm bakery mornings at home.", description:"Six hand-laminated croissants, frozen at exactly the right moment. Proof overnight and bake fresh in your own kitchen.", category:"READY_TO_BAKE", price:1800000, image:"/ready-to-bake.jpg", imagePosition:"52% 53%", badge:"Freezer favourite", featured:true, status:"ACTIVE", stockQuantity:18, lowStockThreshold:6, variants:[{id:"v1",name:"Box of 6",priceAdjustment:0,stockQuantity:18},{id:"v2",name:"Box of 12",priceAdjustment:1500000,stockQuantity:8}], ingredients:"Flour, cultured butter, milk, yeast, sugar, salt", allergens:["Wheat","Dairy","Eggs"], storageInstructions:"Keep frozen for up to 6 weeks.", preparationInstructions:"Proof overnight, brush with egg wash, then bake at 190°C for 18–22 minutes." },
  { id:"p7", slug:"bake-at-home-chocolate-box", name:"Chocolate Croissant Box", shortDescription:"Six chocolate-filled croissants, ready to proof and bake.", description:"Buttery laminated pastry and dark chocolate, prepared for that first warm, flaky bite at home.", category:"READY_TO_BAKE", price:2200000, image:"/ready-to-bake.jpg", imagePosition:"63% 51%", status:"ACTIVE", stockQuantity:9, lowStockThreshold:4, variants:[{id:"v1",name:"Box of 6",priceAdjustment:0,stockQuantity:9}], ingredients:"Flour, cultured butter, dark chocolate, milk, yeast", allergens:["Wheat","Dairy","Eggs","Soy"], storageInstructions:"Keep frozen for up to 6 weeks.", preparationInstructions:"Proof overnight and bake at 190°C until deeply golden." },
  { id:"p8", slug:"weekend-pastry-box", name:"Weekend Pastry Box", shortDescription:"A baker’s selection of six fresh morning pastries.", description:"Six pastries chosen from the morning bake: a changing mix of croissants, danishes and seasonal favourites.", category:"PASTRIES", price:3200000, image:"/pastries.jpg", imagePosition:"51% 52%", badge:"Weekend only", status:"ACTIVE", stockQuantity:4, lowStockThreshold:3, variants:[{id:"v1",name:"Box of 6",priceAdjustment:0,stockQuantity:4}], ingredients:"Selection varies", allergens:["Wheat","Dairy","Eggs","May contain nuts"] },
];

export const deliveryZones = [
  { id:"dz1", name:"Lekki Phase 1", fee:250000, estimate:"Next day · 10am–2pm", active:true },
  { id:"dz2", name:"Ikoyi", fee:350000, estimate:"Next day · 10am–2pm", active:true },
  { id:"dz3", name:"Victoria Island", fee:300000, estimate:"Next day · 10am–2pm", active:true },
  { id:"dz4", name:"Ajah", fee:400000, estimate:"Next day · 12pm–4pm", active:true },
  { id:"dz5", name:"Chevron", fee:300000, estimate:"Next day · 12pm–4pm", active:true },
];

export const cakeOptions = {
  occasions:["Birthday","Wedding","Anniversary","Baby shower","Graduation","Corporate","Just because"],
  sizes:[{name:"6 inch",detail:"Serves 8–10",price:3000000},{name:"8 inch",detail:"Serves 18–22",price:4200000},{name:"10 inch",detail:"Serves 30–35",price:5800000},{name:"Two tier",detail:"Serves 45–55",price:8500000}],
  flavours:[{name:"Vanilla bean",price:0},{name:"Dark chocolate",price:300000},{name:"Red velvet",price:400000},{name:"Carrot & spice",price:500000},{name:"Lemon",price:300000}],
  fillings:[{name:"Vanilla buttercream",price:0},{name:"Berry preserve",price:250000},{name:"Salted caramel",price:300000},{name:"Chocolate ganache",price:400000}],
  designs:[{name:"Soft & minimal",price:0},{name:"Vintage piping",price:800000},{name:"Floral garden",price:1200000},{name:"Statement texture",price:600000}],
};

export const orders: Order[] = [
  {id:"ND-1048",customer:"Dami Adebayo",email:"dami@example.com",total:4650000,status:"PREPARING",date:"2026-09-15",items:3,fulfilment:"delivery"},
  {id:"ND-1047",customer:"Amara Okafor",email:"amara@example.com",total:3800000,status:"CONFIRMED",date:"2026-09-15",items:1,fulfilment:"pickup"},
  {id:"ND-1046",customer:"Teni Balogun",email:"teni@example.com",total:9200000,status:"QUOTE_REQUIRED",date:"2026-09-14",items:1,fulfilment:"delivery"},
  {id:"ND-1045",customer:"Seyi Cole",email:"seyi@example.com",total:7100000,status:"OUT_FOR_DELIVERY",date:"2026-09-14",items:4,fulfilment:"delivery"},
  {id:"ND-1044",customer:"Nneka Obi",email:"nneka@example.com",total:2850000,status:"DELIVERED",date:"2026-09-13",items:2,fulfilment:"delivery"},
];

export function getProduct(slug: string) { return products.find((product) => product.slug === slug); }
