"use client";
import { useState } from "react";
import type { AdminCakeRequest,AdminCoupon,AdminReview } from "@/lib/data/admin";
import { Badge,Button,EmptyState,Input } from "@/components/ui/primitives";
import { formatMoney } from "@/lib/format";
import { useToast } from "@/components/providers";

async function mutate(body:unknown){return fetch("/api/admin/mutate",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)})}

export function CakeRequests({initial}:{initial:AdminCakeRequest[]}){const [items,setItems]=useState(initial);const [selected,setSelected]=useState(initial[0]);const [amount,setAmount]=useState(selected?.quotedTotal?String(selected.quotedTotal/100):"");const notify=useToast();if(!selected)return <EmptyState title="No cake requests" body="New customer requests will appear here."/>;async function save(){const quotedTotal=Math.round(Number(amount)*100);const response=await mutate({action:"cake-quote",id:selected!.id,quotedTotal});if(response.ok){setItems(v=>v.map(item=>item.id===selected!.id?{...item,status:"QUOTE_SENT",quotedTotal}:item));setSelected(v=>v?{...v,status:"QUOTE_SENT",quotedTotal}:v);notify("Cake quote saved.")}else notify("Quote could not be saved.")}return <div className="admin-split"><div className="admin-card request-list">{items.map(item=><article className={item.id===selected.id?"selected":""} key={item.id} onClick={()=>{setSelected(item);setAmount(item.quotedTotal?String(item.quotedTotal/100):"")}}><span className="avatar">{item.customerName.split(" ").map(x=>x[0]).join("").slice(0,2)}</span><div><b>{item.requestNumber} · {item.customerName}</b><small>{item.configuration.occasion} · {item.configuration.size} · {item.requestedDate}</small></div><Badge tone={item.status==="QUOTE_REQUIRED"?"warning":"success"}>{item.status.replaceAll("_"," ")}</Badge></article>)}</div><div className="admin-card request-detail"><span className="overline">{selected.requestNumber} · {selected.status.replaceAll("_"," ")}</span><h2>{selected.configuration.occasion} cake for {selected.customerName}</h2><dl>{["size","flavour","filling","design","colours"].map(key=><div key={key}><dt>{key}</dt><dd>{selected.configuration[key]||"—"}</dd></div>)}<div><dt>Date</dt><dd>{selected.requestedDate}</dd></div></dl><Input label="Quote amount (₦)" type="number" value={amount} onChange={e=>setAmount(e.target.value)}/><p>{selected.email} · {selected.phone}</p><Button disabled={!Number(amount)} onClick={save}>Save quote</Button></div></div>}

export function Coupons({initial}:{initial:AdminCoupon[]}){const notify=useToast();async function create(){const response=await mutate({action:"coupon-create"});if(response.ok){notify("Coupon draft created.");window.location.reload()}else notify("Coupon could not be created.")}return <><div className="admin-page-head compact"><span/><Button onClick={create}>New coupon</Button></div><div className="admin-card table-scroll"><table className="admin-table"><thead><tr><th>Code</th><th>Offer</th><th>Minimum</th><th>Limit</th><th>Status</th></tr></thead><tbody>{initial.map(item=><tr key={item.id}><td><b>{item.code}</b></td><td>{item.type==="PERCENTAGE"?`${item.value}%`:formatMoney(item.value)}</td><td>{formatMoney(item.minimumOrder)}</td><td>{item.usageLimit??"Unlimited"}</td><td><Badge tone={item.active?"success":"neutral"}>{item.active?"Active":"Draft"}</Badge></td></tr>)}</tbody></table></div></>}

export function Reviews({initial}:{initial:AdminReview[]}){const [items,setItems]=useState(initial);const notify=useToast();async function update(id:string,status:"APPROVED"|"REJECTED"){const response=await mutate({action:"review-status",id,status});if(response.ok){setItems(v=>v.map(item=>item.id===id?{...item,status}:item));notify(`Review ${status.toLowerCase()}.`)}else notify("Review could not be updated.")}if(!items.length)return <EmptyState title="No reviews yet" body="Customer reviews will appear here."/>;return <div className="review-admin-grid">{items.map(item=><article className="admin-card" key={item.id}><Badge tone={item.status==="PENDING"?"warning":"success"}>{item.status}</Badge><span className="stars">{"★".repeat(item.rating)}</span><h3>{item.title||item.body}</h3><p>{item.productName} · {item.customerName}</p><div><Button variant="secondary" onClick={()=>update(item.id,"APPROVED")}>Approve</Button><Button variant="ghost" onClick={()=>update(item.id,"REJECTED")}>Reject</Button></div></article>)}</div>}
