export type CustomerText = Record<string, Record<string, string>>;
export const defaultCustomerText: CustomerText = {
  "emails": {
    "your purchase": "your purchase",
    "Review {product}": "Review {product}",
    "How was your order {number}?": "How was your order {number}?",
    "We’d love your feedback": "We’d love your feedback",
    "Hi {name}, thank you for choosing us. These private links verify your purchase and can each be used once:": "Hi {name}, thank you for choosing us. These private links verify your purchase and can each be used once:",
    "Your review will be checked before it appears publicly.": "Your review will be checked before it appears publicly.",
    "Made with care.": "Made with care.",
    "Standard": "Standard",
    "Bakery pickup": "Bakery pickup",
    "Hello {name},": "Hello {name},",
    "Order {number}": "Order {number}",
    "View or download your receipt": "View or download your receipt",
    "Chat with us on WhatsApp": "Chat with us on WhatsApp",
    "Your cake quote {number}": "Your cake quote {number}",
    "Your custom cake quote is ready": "Your custom cake quote is ready",
    "Hi {name}, your quote is {amount}.": "Hi {name}, your quote is {amount}.",
    "there": "there",
    "View and respond to your quote": "View and respond to your quote",
    "This quote is valid until {date}.": "This quote is valid until {date}.",
    "Welcome to {business}": "Welcome to {business}",
    "You’re on the list": "You’re on the list",
    "We’ll share fresh bakes, seasonal boxes and special dates with you.": "We’ll share fresh bakes, seasonal boxes and special dates with you.",
    "Cake request {number} received": "Cake request {number} received",
    "Your cake request is with us": "Your cake request is with us",
    "Thank you, {name}. We’ll review request {number} and reply with the next step.": "Thank you, {name}. We’ll review request {number} and reply with the next step.",
    "{kind} {number}": "{kind} {number}",
    "Your {kind} is ready": "Your {kind} is ready",
    "Hi {name},": "Hi {name},",
    "View or download {number}": "View or download {number}",
    "We received your order": "We received your order",
    "Your order has been received": "Your order has been received",
    "Complete payment to reserve your order. We’ll confirm it as soon as payment succeeds.": "Complete payment to reserve your order. We’ll confirm it as soon as payment succeeds.",
    "Payment confirmed": "Payment confirmed",
    "Your payment is confirmed": "Your payment is confirmed",
    "Your order is paid and is waiting for confirmation from the bakery.": "Your order is paid and is waiting for confirmation from the bakery.",
    "Order confirmed": "Order confirmed",
    "Your order is confirmed": "Your order is confirmed",
    "The bakery has confirmed your order and will begin preparing it on schedule.": "The bakery has confirmed your order and will begin preparing it on schedule.",
    "Your order is being prepared": "Your order is being prepared",
    "We’re preparing your order": "We’re preparing your order",
    "Your order is now in the kitchen and being made with care.": "Your order is now in the kitchen and being made with care.",
    "Your order is ready": "Your order is ready",
    "Your order is ready for its next step. Please check the fulfilment details below.": "Your order is ready for its next step. Please check the fulfilment details below.",
    "Your order is out for delivery": "Your order is out for delivery",
    "Your order is on the way": "Your order is on the way",
    "Your order has left the bakery and is out for delivery.": "Your order has left the bakery and is out for delivery.",
    "Your order has been delivered": "Your order has been delivered",
    "Order delivered": "Order delivered",
    "Your order has been marked as delivered. We hope you enjoy every bite.": "Your order has been marked as delivered. We hope you enjoy every bite.",
    "Your order was refunded": "Your order was refunded",
    "Refund processed": "Refund processed",
    "A full refund has been processed. Your bank may take several business days to display it.": "A full refund has been processed. Your bank may take several business days to display it.",
    "Receipt": "Receipt",
    "Invoice": "Invoice",
    "Quote": "Quote"
  },
  "verified review form": {
    "Thank you for your review.": "Thank you for your review.",
    "It has been verified against your purchase and will appear after moderation.": "It has been verified against your purchase and will appear after moderation.",
    "Verified purchase": "Verified purchase",
    "How was your ": "How was your ",
    "Your private invitation confirms that this review comes from a completed order.": "Your private invitation confirms that this review comes from a completed order.",
    "Your rating": "Your rating",
    "Review title": "Review title",
    "Your review": "Your review",
    "Submitting…": "Submitting…",
    "Submit verified review": "Submit verified review"
  },
  "business document": {
    "This document is generated from the saved database record.": "This document is generated from the saved database record.",
    "Download PDF": "Download PDF",
    "From": "From",
    "no. ": "no. ",
    "Prepared for": "Prepared for",
    "Bill to": "Bill to",
    "Issued": "Issued",
    "Valid until": "Valid until",
    "Due": "Due",
    "Currency": "Currency",
    "Description": "Description",
    "Qty": "Qty",
    "Unit price": "Unit price",
    "Amount": "Amount",
    " · SKU {value1}": " · SKU {value1}",
    "Subtotal": "Subtotal",
    "Discount": "Discount",
    "Delivery": "Delivery",
    "Total": "Total",
    "Paid": "Paid",
    "Refunded": "Refunded",
    "Amount due": "Amount due",
    "Chat with us on WhatsApp": "Chat with us on WhatsApp",
    "Thank you for choosing {value1}.": "Thank you for choosing {value1}.",
    "Customized printable copy. The permanent order and payment records are unchanged.": "Customized printable copy. The permanent order and payment records are unchanged.",
    "Generated from the permanent order record. Keep this document for your records.": "Generated from the permanent order record. Keep this document for your records.",
    "Pay now": "Pay now",
    "Invoice": "Invoice",
    "Receipt": "Receipt",
    "Quote": "Quote",
    "ISSUED": "ISSUED",
    "PAID": "PAID",
    "ACCEPTED": "ACCEPTED",
    "REJECTED": "REJECTED",
    "EXPIRED": "EXPIRED",
    "VOID": "VOID",
    "Continued": "Continued",
    "DESCRIPTION": "DESCRIPTION",
    "QTY": "QTY",
    "UNIT PRICE": "UNIT PRICE",
    "AMOUNT": "AMOUNT",
    "FROM": "FROM",
    "PREPARED FOR": "PREPARED FOR",
    "NOTES": "NOTES",
    "Issued {date}": "Issued {date}",
    "Valid until {date}": "Valid until {date}",
    "Due {date}": "Due {date}",
    "Thank you for choosing {business}.": "Thank you for choosing {business}.",
    "Page {page} of {pages}": "Page {page} of {pages}"
  },
  "print document button": {
    "Print or save PDF": "Print or save PDF"
  },
  "quote response": {
    "Question about quote {value1}": "Question about quote {value1}",
    "This quote has expired": "This quote has expired",
    "Ask us for an updated quote and we’ll confirm current pricing and availability.": "Ask us for an updated quote and we’ll confirm current pricing and availability.",
    "Ask for an updated quote": "Ask for an updated quote",
    "Quote declined": "Quote declined",
    "Your response is saved. You can ask us for a revised quote at any time.": "Your response is saved. You can ask us for a revised quote at any time.",
    "Ask a question": "Ask a question",
    "Final payable amount": "Final payable amount",
    "This includes the accepted cake quote, selected delivery, and applicable tax.": "This includes the accepted cake quote, selected delivery, and applicable tax.",
    "Continue to secure payment": "Continue to secure payment",
    "Choose fulfilment": "Choose fulfilment",
    "Your cake and contact details are already filled in. Add only what we still need to calculate the final total.": "Your cake and contact details are already filled in. Add only what we still need to calculate the final total.",
    "Receive my order by": "Receive my order by",
    "Bakery pickup": "Bakery pickup",
    "Delivery": "Delivery",
    "Delivery is currently unavailable. Choose pickup or contact us to arrange fulfilment.": "Delivery is currently unavailable. Choose pickup or contact us to arrange fulfilment.",
    "Delivery area": "Delivery area",
    "Choose an area": "Choose an area",
    " ": " ",
    "delivery": "delivery",
    "Street address": "Street address",
    "Apartment or unit (optional)": "Apartment or unit (optional)",
    "City": "City",
    "Province code": "Province code",
    "Postal code": "Postal code",
    "Delivery instructions (optional)": "Delivery instructions (optional)",
    "Preparing secure payment…": "Preparing secure payment…",
    "Review total & pay securely": "Review total & pay securely",
    "Ready to continue?": "Ready to continue?",
    "Accept the quote to confirm that you’d like to move ahead with this cake.": "Accept the quote to confirm that you’d like to move ahead with this cake.",
    "Saving…": "Saving…",
    "Accept & continue": "Accept & continue",
    "Decline": "Decline"
  },
  "cart drawer": {
    "Your order": "Your order",
    "Basket": "Basket",
    "Close basket": "Close basket",
    "Your basket is waiting": "Your basket is waiting",
    "Something lovely is only a few taps away.": "Something lovely is only a few taps away.",
    "Browse the bakery": "Browse the bakery",
    "No image": "No image",
    "Decrease quantity": "Decrease quantity",
    "Increase quantity": "Increase quantity",
    "Remove": "Remove",
    "Subtotal": "Subtotal",
    "Delivery is calculated at checkout.": "Delivery is calculated at checkout.",
    "View basket": "View basket",
    "Checkout": "Checkout"
  },
  "cart page": {
    "Your basket is empty": "Your basket is empty",
    "There’s plenty still warm on the counter.": "There’s plenty still warm on the counter.",
    "Browse the bakery": "Browse the bakery",
    "Your treats": "Your treats",
    "Clear basket": "Clear basket",
    "No image": "No image",
    "Remove": "Remove",
    "Order summary": "Order summary",
    "Subtotal": "Subtotal",
    "Delivery": "Delivery",
    "Calculated next": "Calculated next",
    "Estimated total": "Estimated total",
    "Continue to checkout": "Continue to checkout",
    "Secure checkout · Carefully prepared · Clear delivery updates": "Secure checkout · Carefully prepared · Clear delivery updates"
  },
  "checkout flow": {
    "Add {value1} more before continuing.": "Add {value1} more before continuing.",
    "Your basket is empty": "Your basket is empty",
    "Add a treat before starting checkout.": "Add a treat before starting checkout.",
    "Browse the bakery": "Browse the bakery",
    "Online ordering is paused": "Online ordering is paused",
    "Please check back later or contact the bakery for help with an order.": "Please check back later or contact the bakery for help with an order.",
    "Contact the bakery": "Contact the bakery",
    "Your details": "Your details",
    "Who is this order for?": "Who is this order for?",
    "Full name": "Full name",
    "Email address": "Email address",
    "Phone number": "Phone number",
    "Continue to fulfilment": "Continue to fulfilment",
    "Fulfilment": "Fulfilment",
    "How should we get it to you?": "How should we get it to you?",
    "Delivery is currently unavailable. You can collect your order from the bakery.": "Delivery is currently unavailable. You can collect your order from the bakery.",
    "Delivery": "Delivery",
    "To your Canadian delivery address": "To your Canadian delivery address",
    "Pickup": "Pickup",
    "Collect from our bakery": "Collect from our bakery",
    "Delivery area": "Delivery area",
    "Choose your area": "Choose your area",
    " · {value1} minimum": " · {value1} minimum",
    "Street address": "Street address",
    "Apartment, suite or unit (optional)": "Apartment, suite or unit (optional)",
    "City": "City",
    "Province or territory": "Province or territory",
    "Choose one": "Choose one",
    "Postal code": "Postal code",
    "A1A 1A1": "A1A 1A1",
    "Delivery notes (optional)": "Delivery notes (optional)",
    "Gate code, landmark or a helpful note": "Gate code, landmark or a helpful note",
    "Pickup details": "Pickup details",
    "and a collection time will be confirmed with your order.": "and a collection time will be confirmed with your order.",
    "Back": "Back",
    "Review order": "Review order",
    "Final check": "Final check",
    "Review your order": "Review your order",
    "Contact": "Contact",
    "Edit": "Edit",
    "Deliver to": "Deliver to",
    "Collection": "Collection",
    "Have a coupon?": "Have a coupon?",
    "Enter code": "Enter code",
    "Applying…": "Applying…",
    "Applied ✓": "Applied ✓",
    "saved you ": "saved you ",
    "Secure payment with Stripe": "Secure payment with Stripe",
    "You’ll continue to Stripe to pay. Your order is confirmed only after Stripe securely verifies the payment.": "You’ll continue to Stripe to pay. Your order is confirmed only after Stripe securely verifies the payment.",
    "Opening secure payment…": "Opening secure payment…",
    "Continue to payment": "Continue to payment",
    "Order summary": "Order summary",
    "Show": "Show",
    "No image": "No image",
    "· Qty ": "· Qty ",
    "Subtotal": "Subtotal",
    "Free": "Free",
    "Discount": "Discount",
    "Total": "Total",
    "Details": "Details",
    "Review": "Review",
    "Information": "Information"
  },
  "payment result": {
    "Payment status is unavailable.": "Payment status is unavailable.",
    "Your payment wasn’t completed.": "Your payment wasn’t completed.",
    "Your order is still awaiting payment.": "Your order is still awaiting payment.",
    "We’re confirming your payment.": "We’re confirming your payment.",
    "No payment was confirmed. You can safely try again; stock and coupon availability will be checked first.": "No payment was confirmed. You can safely try again; stock and coupon availability will be checked first.",
    "Nothing has been charged. Resume the secure checkout whenever you’re ready.": "Nothing has been charged. Resume the secure checkout whenever you’re ready.",
    "This usually takes only a few seconds. You can leave this page; Stripe’s signed confirmation will update your order.": "This usually takes only a few seconds. You can leave this page; Stripe’s signed confirmation will update your order.",
    "Payment status": "Payment status",
    "Order #": "Order #",
    " ": " ",
    "What happens next?": "What happens next?",
    "Checking for Stripe confirmation…": "Checking for Stripe confirmation…",
    "Track this order": "Track this order",
    "Preparing payment…": "Preparing payment…",
    "Try payment again": "Try payment again",
    "Resume secure payment": "Resume secure payment",
    "Continue shopping": "Continue shopping",
    "Return to checkout": "Return to checkout"
  },
  "product carousel": {
    "PASTRIES": "PASTRIES",
    "READY TO BAKE": "READY TO BAKE",
    "CUSTOM CAKES": "CUSTOM CAKES",
    "Product {value1} of {value2}: {value3}": "Product {value1} of {value2}: {value3}",
    "View {value1}": "View {value1}",
    "No product image uploaded": "No product image uploaded",
    "View details": "View details",
    "Add to basket": "Add to basket",
    "Choose options": "Choose options",
    "Currently unavailable": "Currently unavailable",
    "Previous product": "Previous product",
    "Choose a product slide": "Choose a product slide",
    "Show {value1}": "Show {value1}",
    "of ": "of ",
    "Next product": "Next product",
    "Play automatic product slides": "Play automatic product slides",
    "Pause automatic product slides": "Pause automatic product slides",
    "Play": "Play",
    "Pause": "Pause"
  },
  "catalogue": {
    "Search catalogue": "Search catalogue",
    "Search the bakery": "Search the bakery",
    "Filters & budget": "Filters & budget",
    "Sort by": "Sort by",
    "Featured": "Featured",
    "Newest": "Newest",
    "Price: low to high": "Price: low to high",
    "Price: high to low": "Price: high to low",
    "Close filters": "Close filters",
    "Category": "Category",
    "All treats": "All treats",
    "Fresh pastries": "Fresh pastries",
    "Ready to bake": "Ready to bake",
    "Celebration cakes": "Celebration cakes",
    "Availability": "Availability",
    "Available now": "Available now",
    "Show": "Show",
    "products": "products",
    "treat": "treat",
    "treats": "treats",
    " within {value1}": " within {value1}",
    "Nothing matched that search": "Nothing matched that search",
    "Cake ideas across your budget": "Cake ideas across your budget",
    "Explore simpler and more detailed builds without spending your whole budget.": "Explore simpler and more detailed builds without spending your whole budget.",
    "Ideas up to ": "Ideas up to ",
    "combinations": "combinations",
    "cake": "cake"
  },
  "product reviews": {
    "Verified customers": "Verified customers",
    "Reviews of ": "Reviews of ",
    "review": "review",
    "reviews": "reviews",
    "No verified reviews yet": "No verified reviews yet",
    "Reviews can only be submitted through the private link emailed after a completed order.": "Reviews can only be submitted through the private link emailed after a completed order.",
    "Customer review": "Customer review",
    "· Verified purchase": "· Verified purchase"
  },
  "product card": {
    "PASTRIES": "PASTRIES",
    "READY TO BAKE": "READY TO BAKE",
    "CUSTOM CAKES": "CUSTOM CAKES",
    "No image uploaded": "No image uploaded",
    "Sold out": "Sold out",
    "Add {value1} to basket": "Add {value1} to basket",
    "Choose options for {value1}": "Choose options for {value1}"
  },
  "product purchase": {
    "This product does not have an available option.": "This product does not have an available option.",
    "Choose an option": "Choose an option",
    "Included": "Included",
    "Decrease quantity": "Decrease quantity",
    "Increase quantity": "Increase quantity",
    "Unavailable": "Unavailable",
    "Add to basket · {value1}": "Add to basket · {value1}",
    "This option is currently unavailable.": "This option is currently unavailable.",
    "Only {value1} left for this bake.": "Only {value1} left for this bake.",
    "Available to add to your basket.": "Available to add to your basket."
  },
  "product gallery": {
    "No product image has been uploaded.": "No product image has been uploaded.",
    "View image: {value1}": "View image: {value1}"
  },
  "errors": {
    "Please choose a JPG, PNG or WebP image.": "Please choose a JPG, PNG or WebP image.",
    "Please choose an image smaller than 5 MB.": "Please choose an image smaller than 5 MB.",
    "Choose an option to continue.": "Choose an option to continue.",
    "Enter a valid Canadian postal code.": "Enter a valid Canadian postal code.",
    "Choose a province or territory.": "Choose a province or territory.",
    "Enter a valid city.": "Enter a valid city.",
    "Enter a complete delivery address.": "Enter a complete delivery address.",
    "Choose a delivery area.": "Choose a delivery area.",
    "Enter a valid phone number.": "Enter a valid phone number.",
    "Enter at least two characters for the name.": "Enter at least two characters for the name.",
    "Too many requests. Please wait before trying again.": "Too many requests. Please wait before trying again.",
    "This request is temporarily unavailable. Please try again shortly.": "This request is temporarily unavailable. Please try again shortly.",
    "Sale price cannot exceed the regular price.": "Sale price cannot exceed the regular price.",
    "An active product needs an active variant.": "An active product needs an active variant.",
    "One of the selected cake options is unavailable.": "One of the selected cake options is unavailable.",
    "Choose a date with enough preparation time.": "Choose a date with enough preparation time.",
    "Delivery is not currently available.": "Delivery is not currently available.",
    "Pickup is not currently available.": "Pickup is not currently available.",
    "Your basket is empty.": "Your basket is empty.",
    "Choose a valid quantity.": "Choose a valid quantity.",
    "A product in your basket is no longer available.": "A product in your basket is no longer available.",
    "This item’s price needs review.": "This item’s price needs review.",
    "The order minimum needs review.": "The order minimum needs review.",
    "The delivery minimum needs review.": "The delivery minimum needs review.",
    "The delivery fee is invalid.": "The delivery fee is invalid.",
    "The configured tax rate needs review.": "The configured tax rate needs review.",
    "That coupon is not active.": "That coupon is not active.",
    "That coupon is not active yet.": "That coupon is not active yet.",
    "That coupon has expired.": "That coupon has expired.",
    "That coupon has reached its usage limit.": "That coupon has reached its usage limit.",
    "That coupon does not apply to these items.": "That coupon does not apply to these items.",
    "A product is no longer available.": "A product is no longer available.",
    "Invalid request origin.": "Invalid request origin.",
    "Please complete every review field.": "Please complete every review field.",
    "This review link is invalid.": "This review link is invalid.",
    "This review link has already been used.": "This review link has already been used.",
    "This review link is not available.": "This review link is not available.",
    "We couldn’t save your review. Please try again.": "We couldn’t save your review. Please try again.",
    "Missing Stripe signature.": "Missing Stripe signature.",
    "Invalid Stripe signature.": "Invalid Stripe signature.",
    "Invalid Stripe refund.": "Invalid Stripe refund.",
    "Webhook processing failed.": "Webhook processing failed.",
    "Invalid Checkout Session.": "Invalid Checkout Session.",
    "Invalid analytics event.": "Invalid analytics event.",
    "Invalid analytics timestamp.": "Invalid analytics timestamp.",
    "Analytics is temporarily unavailable.": "Analytics is temporarily unavailable.",
    "Scheduled notifications failed.": "Scheduled notifications failed.",
    "Please complete the contact form.": "Please complete the contact form.",
    "We couldn’t send your message. Please try again.": "We couldn’t send your message. Please try again.",
    "Enter a valid email address.": "Enter a valid email address.",
    "We couldn’t subscribe you. Please try again.": "We couldn’t subscribe you. Please try again.",
    "That delivery zone is unavailable.": "That delivery zone is unavailable.",
    "That coupon is not valid.": "That coupon is not valid.",
    "We couldn’t create your order. Please try again.": "We couldn’t create your order. Please try again.",
    "Document not found.": "Document not found.",
    "Check your order number and email.": "Check your order number and email.",
    "No matching order was found.": "No matching order was found.",
    "Enter a valid refund amount and reason.": "Enter a valid refund amount and reason.",
    "The order could not be verified for auditing.": "The order could not be verified for auditing.",
    "The refund was not sent because its audit record could not be verified.": "The refund was not sent because its audit record could not be verified.",
    "Stripe could not complete the refund.": "Stripe could not complete the refund.",
    "Invalid payment session.": "Invalid payment session.",
    "Payment session not found.": "Payment session not found.",
    "Too many code requests. Please wait before trying again.": "Too many code requests. Please wait before trying again.",
    "Admin email authentication is not configured yet.": "Admin email authentication is not configured yet.",
    "The current product could not be verified for auditing.": "The current product could not be verified for auditing.",
    "Product category is missing.": "Product category is missing.",
    "A variant does not belong to this product.": "A variant does not belong to this product.",
    "An image does not belong to this product.": "An image does not belong to this product.",
    "A product variant could not be updated.": "A product variant could not be updated.",
    "A removed variant could not be archived.": "A removed variant could not be archived.",
    "Product image ordering could not be updated.": "Product image ordering could not be updated.",
    "A product image could not be removed.": "A product image could not be removed.",
    "The product was saved, but its audit record could not be verified.": "The product was saved, but its audit record could not be verified.",
    "Product could not be found.": "Product could not be found.",
    "Product could not be duplicated.": "Product could not be duplicated.",
    "The product copy was created without its variants.": "The product copy was created without its variants.",
    "The product copy was created without its images.": "The product copy was created without its images.",
    "The product copy was saved, but its audit record could not be verified.": "The product copy was saved, but its audit record could not be verified.",
    "Product variants could not be saved.": "Product variants could not be saved.",
    "Please complete the cake details.": "Please complete the cake details.",
    "Use a JPG, PNG, or WebP image up to 5 MB.": "Use a JPG, PNG, or WebP image up to 5 MB.",
    "The request body is invalid.": "The request body is invalid.",
    "We couldn’t price this cake. Please try again.": "We couldn’t price this cake. Please try again.",
    "Order not found.": "Order not found.",
    "This order is already paid.": "This order is already paid.",
    "We couldn’t restart this payment. Please try again.": "We couldn’t restart this payment. Please try again.",
    "This quote link is not valid.": "This quote link is not valid.",
    "That code is invalid or has expired.": "That code is invalid or has expired.",
    "Enter the six-digit code from your email.": "Enter the six-digit code from your email.",
    "Admin authentication is not configured yet.": "Admin authentication is not configured yet.",
    "Choose a valid image and provide alternative text.": "Choose a valid image and provide alternative text.",
    "Use a JPG, PNG, WebP, or AVIF image up to 5 MB.": "Use a JPG, PNG, WebP, or AVIF image up to 5 MB.",
    "A product can have up to 12 images.": "A product can have up to 12 images.",
    "Image upload failed.": "Image upload failed.",
    "Image metadata could not be saved.": "Image metadata could not be saved.",
    "The image was saved, but its audit record could not be verified.": "The image was saved, but its audit record could not be verified.",
    "We could not prepare this order. Please check the details and try again.": "We could not prepare this order. Please check the details and try again.",
    "Payment could not be started. Please try again.": "Payment could not be started. Please try again.",
    "Check the presentation options and try again.": "Check the presentation options and try again.",
    "Presentation changes could not be saved.": "Presentation changes could not be saved.",
    "Percentage discounts cannot exceed 100%.": "Percentage discounts cannot exceed 100%.",
    "Coupon expiry must be after its start date.": "Coupon expiry must be after its start date.",
    "Invalid admin update.": "Invalid admin update.",
    "The current value could not be verified for auditing.": "The current value could not be verified for auditing.",
    "Inventory update failed.": "Inventory update failed.",
    "Order status transition failed.": "Order status transition failed.",
    "Order note update failed.": "Order note update failed.",
    "The quote could not be issued.": "The quote could not be issued.",
    "The quote email could not be queued.": "The quote email could not be queued.",
    "Check the business settings and try again.": "Check the business settings and try again.",
    "Check the storefront settings and try again.": "Check the storefront settings and try again.",
    "Update this cake from its linked order. The payment and order stages control its progress.": "Update this cake from its linked order. The payment and order stages control its progress.",
    "The update could not be saved.": "The update could not be saved.",
    "The update was saved, but its audit record could not be verified.": "The update was saved, but its audit record could not be verified.",
    "Choose a valid document action.": "Choose a valid document action.",
    "Document reference is unavailable.": "Document reference is unavailable.",
    "This document has expired and cannot be shared.": "This document has expired and cannot be shared.",
    "Customer email is unavailable.": "Customer email is unavailable.",
    "The email could not be sent.": "The email could not be sent.",
    "Please check the highlighted order details.": "Please check the highlighted order details.",
    "We couldn’t calculate the order. Please try again.": "We couldn’t calculate the order. Please try again.",
    "No SKU": "No SKU",
    "We couldn’t save your review.": "We couldn’t save your review.",
    "We could not save your response. Please try again.": "We could not save your response. Please try again.",
    "We couldn’t validate your cake.": "We couldn’t validate your cake.",
    "We couldn’t validate this order.": "We couldn’t validate this order.",
    "Payment could not be restarted.": "Payment could not be restarted.",
    "Something went wrong": "Something went wrong",
    "We couldn’t load this just now. Please try again.": "We couldn’t load this just now. Please try again.",
    "Try again": "Try again",
    "Pagination": "Pagination",
    "Previous page": "Previous page",
    "Next page": "Next page",
    "Close dialog": "Close dialog",
    "We couldn’t find that order.": "We couldn’t find that order.",
    "We couldn’t send your message.": "We couldn’t send your message.",
    "Please try again.": "Please try again."
  },
  "cake builder": {
    "Please choose a date at least {value1} hours from now.": "Please choose a date at least {value1} hours from now.",
    "Request received": "Request received",
    "Your cake story starts here.": "Your cake story starts here.",
    "We’ve saved your configuration as": "We’ve saved your configuration as",
    ". A baker will review the details and reply with the next step.": ". A baker will review the details and reply with the next step.",
    "Build another cake": "Build another cake",
    "Step": "Step",
    "of ": "of ",
    "What are we celebrating?": "What are we celebrating?",
    "How many are we serving?": "How many are we serving?",
    "Choose your cake flavour": "Choose your cake flavour",
    "Choose a filling": "Choose a filling",
    "Set the design direction": "Set the design direction",
    "What colours are speaking to you?": "What colours are speaking to you?",
    "Name two or three colours. We’ll balance them beautifully.": "Name two or three colours. We’ll balance them beautifully.",
    "Colour palette": "Colour palette",
    "e.g. soft pink, ivory and deep berry": "e.g. soft pink, ivory and deep berry",
    "Add a cake inscription": "Add a cake inscription",
    "Optional. Short messages fit most beautifully.": "Optional. Short messages fit most beautifully.",
    "Inscription": "Inscription",
    "Happy birthday, Amara": "Happy birthday, Amara",
    "Show us what inspired you": "Show us what inspired you",
    "Optional. We’ll use your image as a direction, not make an exact copy.": "Optional. We’ll use your image as a direction, not make an exact copy.",
    "Upload an inspiration image": "Upload an inspiration image",
    "JPG, PNG or WebP · up to 5 MB": "JPG, PNG or WebP · up to 5 MB",
    "When do you need your cake?": "When do you need your cake?",
    "We need at least": "We need at least",
    "hours to make something wonderful.": "hours to make something wonderful.",
    "Collection or delivery date": "Collection or delivery date",
    "Dates remain subject to bakery capacity until confirmed.": "Dates remain subject to bakery capacity until confirmed.",
    "Everything look delicious?": "Everything look delicious?",
    "Review your choices before sending them to the bakery.": "Review your choices before sending them to the bakery.",
    "Inspiration": "Inspiration",
    "Your name": "Your name",
    "Email address": "Email address",
    "Phone number": "Phone number",
    "Anything else we should know?": "Anything else we should know?",
    "Optional notes for our bakers": "Optional notes for our bakers",
    "Back": "Back",
    "Validating…": "Validating…",
    "Request your quote": "Request your quote",
    "Send cake request": "Send cake request",
    "Starting estimate": "Starting estimate",
    "Estimated total": "Estimated total",
    "—": "—",
    "selections · View": "selections · View",
    "Size": "Size",
    "Flavour": "Flavour",
    "Style": "Style",
    "Your cake": "Your cake",
    "Final price follows baker review.": "Final price follows baker review.",
    "Final price confirmed after review.": "Final price confirmed after review.",
    "Included": "Included",
    "Occasion": "Occasion",
    "Filling": "Filling",
    "Design": "Design",
    "Colours": "Colours",
    "Date": "Date",
    "Review": "Review",
    "{stage}, completed": "{stage}, completed"
  },
  "track order": {
    "paid": "paid",
    "confirmed": "confirmed",
    "preparing": "preparing",
    "ready": "ready",
    "out for delivery": "out for delivery",
    "delivered": "delivered",
    "cancelled": "cancelled",
    "refunded": "refunded",
    "Order number": "Order number",
    "ND-12345678": "ND-12345678",
    "Email address": "Email address",
    "Looking…": "Looking…",
    "Find my order": "Find my order",
    "Order ": "Order ",
    "Your order is awaiting payment.": "Your order is awaiting payment.",
    "Your order is {value1}.": "Your order is {value1}.",
    "Pickup": "Pickup",
    "Delivery": "Delivery",
    "details will be confirmed by the bakery.": "details will be confirmed by the bakery.",
    "Updated": "Updated",
    "Track a different order": "Track a different order",
    "Order confirmed": "Order confirmed",
    "Preparing": "Preparing",
    "Ready": "Ready",
    "Out for delivery": "Out for delivery",
    "Delivered": "Delivered"
  },
  "contact form": {
    "Your note is with us.": "Your note is with us.",
    "We’ll reply within one bakery day.": "We’ll reply within one bakery day.",
    "Send another message": "Send another message",
    "Your name": "Your name",
    "Email address": "Email address",
    "Phone number (optional)": "Phone number (optional)",
    "What can we help with?": "What can we help with?",
    "General question": "General question",
    "Existing order": "Existing order",
    "Custom cake": "Custom cake",
    "Corporate order": "Corporate order",
    "Your message": "Your message",
    "Sending…": "Sending…",
    "Send message": "Send message"
  },
  "brand logo": {
    "Ndeeelicious Delight": "Ndeeelicious Delight"
  },
  "newsletter form": {
    "✓ You’re on the list. Welcome.": "✓ You’re on the list. Welcome.",
    "Email address": "Email address",
    "Subscribe": "Subscribe",
    "…": "…",
    "→": "→"
  },
  "storefront shell": {
    "Skip to main content": "Skip to main content",
    "Chat with {value1} on WhatsApp": "Chat with {value1} on WhatsApp",
    "wa": "wa"
  },
  "footer": {
    "Instagram": "Instagram",
    "ig": "ig",
    "WhatsApp": "WhatsApp",
    "wa": "wa",
    "Explore": "Explore",
    "Visit & help": "Visit & help",
    "Delivery information": "Delivery information",
    "Frequently asked": "Frequently asked",
    "Contact us": "Contact us",
    "Privacy": "Privacy",
    "Terms": "Terms",
    "Returns & cancellations": "Returns & cancellations"
  },
  "header": {
    "Open navigation": "Open navigation",
    "{value1} home": "{value1} home",
    "Primary": "Primary",
    "Search": "Search",
    "Contact": "Contact",
    "Open basket, {value1} items": "Open basket, {value1} items",
    "Basket": "Basket",
    "Close navigation": "Close navigation",
    "Contact us": "Contact us",
    "Search products": "Search products",
    "Search cakes, pastries, flavours…": "Search cakes, pastries, flavours…",
    "Close search": "Close search",
    "{value1} suggestions": "{value1} suggestions",
    "No treats found": "No treats found",
    "No image uploaded": "No image uploaded",
    "Browse all products": "Browse all products"
  },
  "Page: (storefront)": {
    "No featured products are currently published.": "No featured products are currently published.",
    "Follow along ↗": "Follow along ↗"
  },
  "layout": {
    "Skip to checkout": "Skip to checkout",
    "Ndeeelicious Delight home": "Ndeeelicious Delight home",
    "Secure checkout": "Secure checkout",
    "Checkout policies and support": "Checkout policies and support",
    "Returns & cancellations": "Returns & cancellations",
    "Delivery & pickup": "Delivery & pickup",
    "Terms": "Terms",
    "Privacy": "Privacy",
    "Contact us": "Contact us"
  },
  "Page: ready-to-bake": {
    "No ready-to-bake products are currently published.": "No ready-to-bake products are currently published.",
    "Available across Halifax HRM": "Available across Halifax HRM",
    "Find us in stores": "Find us in stores",
    "Meat pies, chicken pies and beef sausage rolls, frozen and ready to bake. Contact each store for current stock, prices and opening hours.": "Meat pies, chicken pies and beef sausage rolls, frozen and ready to bake. Contact each store for current stock, prices and opening hours.",
    "For purchases made in store, contact that retailer with your receipt for support.": "For purchases made in store, contact that retailer with your receipt for support."
  },
  "Page: Review": {
    "Review invitation": "Review invitation",
    "This link is no longer available.": "This link is no longer available.",
    "Review links are single-use and expire after 90 days. Contact the bakery if you believe this is a mistake.": "Review links are single-use and expire after 90 days. Contact the bakery if you believe this is a mistake."
  },
  "Page: delivery-information": {
    " · {value1} minimum": " · {value1} minimum",
    "No delivery zones are currently active.": "No delivery zones are currently active.",
    "Delivery ordering is currently paused.": "Delivery ordering is currently paused.",
    " Pickup remains available.": " Pickup remains available.",
    "current bakery setting": "current bakery setting",
    "{value1}-hour minimum": "{value1}-hour minimum"
  },
  "Page: contact": {
    "Email": "Email",
    "Phone": "Phone",
    "WhatsApp": "WhatsApp",
    "Chat with us on WhatsApp": "Chat with us on WhatsApp",
    "Bakery hours": "Bakery hours",
    "Location": "Location"
  },
  "Page: custom-cakes": {
    "Most cakes need at least ": "Most cakes need at least ",
    "hours.": "hours."
  },
  "Page: Product": {
    "Product not found": "Product not found",
    "Home": "Home",
    "Shop": "Shop",
    " ": " ",
    "Description": "Description",
    "Ingredients & allergens": "Ingredients & allergens",
    "Contains:": "Contains:",
    "Storage & preparation": "Storage & preparation",
    "You may also love": "You may also love",
    "Shop all": "Shop all"
  },
  "not found": {
    "This treat has left the counter.": "This treat has left the counter.",
    "Let’s get you back to something delicious.": "Let’s get you back to something delicious.",
    "Browse the bakery": "Browse the bakery"
  },
  "page titles": {
    "{business} — Custom Cakes & Nigerian-Style Pies": "{business} — Custom Cakes & Nigerian-Style Pies",
    "Your basket": "Your basket",
    "Shop the bakery": "Shop the bakery",
    "Browse the live bakery catalogue.": "Browse the live bakery catalogue.",
    "Privacy policy": "Privacy policy",
    "Pastries": "Pastries",
    "Contact": "Contact",
    "Email": "Email",
    "Phone": "Phone",
    "WhatsApp": "WhatsApp",
    "Chat with us on WhatsApp": "Chat with us on WhatsApp",
    "Bakery hours": "Bakery hours",
    "Location": "Location",
    "Leave a review": "Leave a review",
    "Review invitation": "Review invitation",
    "This link is no longer available.": "This link is no longer available.",
    "Review links are single-use and expire after 90 days. Contact the bakery if you believe this is a mistake.": "Review links are single-use and expire after 90 days. Contact the bakery if you believe this is a mistake.",
    "Refund policy": "Refund policy",
    "Delivery information": "Delivery information",
    " · {value1} minimum": " · {value1} minimum",
    "No delivery zones are currently active.": "No delivery zones are currently active.",
    "Delivery ordering is currently paused.": "Delivery ordering is currently paused.",
    " Pickup remains available.": " Pickup remains available.",
    "current bakery setting": "current bakery setting",
    "{value1}-hour minimum": "{value1}-hour minimum",
    "Frequently asked questions": "Frequently asked questions",
    "Build your custom cake": "Build your custom cake",
    "Create a cake made especially for your celebration.": "Create a cake made especially for your celebration.",
    "Most cakes need at least ": "Most cakes need at least ",
    "hours.": "hours.",
    "Ready to bake": "Ready to bake",
    "No ready-to-bake products are currently published.": "No ready-to-bake products are currently published.",
    "Available across Halifax HRM": "Available across Halifax HRM",
    "Find us in stores": "Find us in stores",
    "Meat pies, chicken pies and beef sausage rolls, frozen and ready to bake. Contact each store for current stock, prices and opening hours.": "Meat pies, chicken pies and beef sausage rolls, frozen and ready to bake. Contact each store for current stock, prices and opening hours.",
    "For purchases made in store, contact that retailer with your receipt for support.": "For purchases made in store, contact that retailer with your receipt for support.",
    "Track your order": "Track your order",
    "About": "About",
    "Terms": "Terms"
  }
};

export function mergeCustomerText(saved: CustomerText = {}): CustomerText {
  const result: CustomerText = {};
  for (const group of new Set([...Object.keys(defaultCustomerText), ...Object.keys(saved)])) {
    result[group] = { ...defaultCustomerText[group], ...saved[group] };
  }
  return result;
}

/** Values are interpolated as plain text; callers escape them when building HTML email. */
export function customerText(copy: CustomerText, group: string) {
  return (original: string | undefined, values: Record<string, string | number> = {}) => {
    if (original === undefined) return "";
    const template = copy[group]?.[original] ?? copy.errors?.[original] ?? defaultCustomerText[group]?.[original] ?? defaultCustomerText.errors?.[original] ?? original;
    return template.replace(/\{(\w+)\}/g, (match, key: string) =>
      Object.hasOwn(values, key) ? String(values[key]) : match,
    );
  };
}
